<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tentang Kami</name>
   <tag></tag>
   <elementGuidId>26ec9684-a3f4-4003-8619-dac0df2390c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='nav-menu-item-3175']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-menu-item-3175 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0d6ad0d6-3583-49a6-afa4-1bea53190357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://kanggo.id/about-us/</value>
      <webElementGuid>5a5622ec-c2f0-40fe-8355-c24de4974bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tentang Kami</value>
      <webElementGuid>4041c695-536b-4909-a930-074984b37d4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-menu-item-3175&quot;)/a[1]</value>
      <webElementGuid>91d9ece1-599c-461c-b73c-c2b61a0a35d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav-menu-item-3175']/a</value>
      <webElementGuid>0d737683-63b8-42be-8c86-21cd0577bf9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tentang Kami')]</value>
      <webElementGuid>88c7b686-1749-486f-b0f8-52f8886e6787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Layanan'])[1]/preceding::a[1]</value>
      <webElementGuid>3c544212-a070-42b9-99f8-e611220bfedb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jasa Pipa Mampet &amp; Instalasi Pipa'])[1]/preceding::a[2]</value>
      <webElementGuid>bd04d60e-327c-4e6e-80d5-26561e39f89a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tentang Kami']/parent::*</value>
      <webElementGuid>c65f1ce6-2c77-4994-83c7-6eeca2896296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://kanggo.id/about-us/')]</value>
      <webElementGuid>1bb0c109-fb5e-4c94-8e48-7ab41cd981b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>c25a1726-a1c8-445f-abe9-fefa2d4f0e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://kanggo.id/about-us/' and (text() = 'Tentang Kami' or . = 'Tentang Kami')]</value>
      <webElementGuid>08f94e2f-0840-493e-8ed4-605021a5e18d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
