<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Download Sekarang_tp-rs-img lazy-loaded_24fac9</name>
   <tag></tag>
   <elementGuidId>21796f30-af14-4d0d-ae29-c3569939164a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='slider-2-slide-2-layer-5']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#slider-2-slide-2-layer-5 > img.tp-rs-img.lazy-loaded.ls-is-cached.lazyloaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9126e961-ecf2-4489-b6fd-9a24b7baf1e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>308</value>
      <webElementGuid>e6989ec2-3235-48fc-b1d2-c4ca8a09f297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>103</value>
      <webElementGuid>b31f3580-1858-424c-bdcd-c781fe59bcca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>//development.kanggo.id/wp-content/uploads/2022/01/Appstr-btn.webp</value>
      <webElementGuid>f5a6bc40-5427-4339-9d47-90e0d911ab9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tp-rs-img lazy-loaded ls-is-cached lazyloaded</value>
      <webElementGuid>fdf9d745-3702-4492-938f-f0a3b621c96c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//development.kanggo.id/wp-content/uploads/2022/01/Appstr-btn.webp</value>
      <webElementGuid>cca64652-17ae-4c2c-bfa3-24e0ab0c80f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src-rs-ref</name>
      <type>Main</type>
      <value>https://development.kanggo.id/wp-content/uploads/2022/01/Appstr-btn.webp</value>
      <webElementGuid>1a5f374b-1a24-4d10-8f2c-81598cf371a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slider-2-slide-2-layer-5&quot;)/img[@class=&quot;tp-rs-img lazy-loaded ls-is-cached lazyloaded&quot;]</value>
      <webElementGuid>70af7aac-7f66-4cd4-9326-329880d0893d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='slider-2-slide-2-layer-5']/img</value>
      <webElementGuid>1ddc4bef-3204-4d0a-9542-30b1ccd7d24f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//rs-layer-wrap[4]/rs-loop-wrap/rs-mask-wrap/a/img</value>
      <webElementGuid>bce1f4e8-f510-4a55-808b-593f486dd532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//development.kanggo.id/wp-content/uploads/2022/01/Appstr-btn.webp']</value>
      <webElementGuid>3b8b5362-f419-47fd-b62e-4316839dca8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='slider-2-slide-2-layer-3']/img</value>
      <webElementGuid>0b30c8d2-5377-448f-b086-53717dc81613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//rs-mask-wrap/a/img</value>
      <webElementGuid>dfcb3f3d-d8a4-4bdc-bd0a-ea724df82073</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//development.kanggo.id/wp-content/uploads/2022/01/Gplay-btn.webp']</value>
      <webElementGuid>27852e88-2b03-45b7-9fac-a609dadd00dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
