<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Download Sekarang_tp-rs-img lazy-loaded ls-is-cached lazyloaded</name>
   <tag></tag>
   <elementGuidId>c10768b4-2bc2-48d7-b14d-49310e748329</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='slider-2-slide-2-layer-5']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#slider-2-slide-2-layer-5 > img.tp-rs-img.lazy-loaded.ls-is-cached.lazyloaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2c4d8ea3-9e0e-42b9-85b2-6440baae2091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>308</value>
      <webElementGuid>9dba5a5f-d4a4-4e8e-be34-f204f814be3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>103</value>
      <webElementGuid>821f75ed-8faa-4fef-b5e2-c442c8ec2da0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>//development.kanggo.id/wp-content/uploads/2022/01/Appstr-btn.webp</value>
      <webElementGuid>fae6539d-0546-445a-99a7-f632f64bdee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tp-rs-img lazy-loaded ls-is-cached lazyloaded</value>
      <webElementGuid>2610003e-3769-4a6e-8db4-a6a19042cd30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//development.kanggo.id/wp-content/uploads/2022/01/Appstr-btn.webp</value>
      <webElementGuid>53853228-6642-4db9-a0ce-04996c56b8e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src-rs-ref</name>
      <type>Main</type>
      <value>https://development.kanggo.id/wp-content/uploads/2022/01/Appstr-btn.webp</value>
      <webElementGuid>3e96368c-4873-457b-9177-267c5dab0383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slider-2-slide-2-layer-5&quot;)/img[@class=&quot;tp-rs-img lazy-loaded ls-is-cached lazyloaded&quot;]</value>
      <webElementGuid>7f7ae7a8-f0be-4a6d-8d9b-ca1f02e5664b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='slider-2-slide-2-layer-5']/img</value>
      <webElementGuid>0dd7c4d8-0233-4523-94c5-e7840e73e06f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//rs-layer-wrap[4]/rs-loop-wrap/rs-mask-wrap/a/img</value>
      <webElementGuid>4ba6b3a6-f037-4012-b947-dba03b322e42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//development.kanggo.id/wp-content/uploads/2022/01/Appstr-btn.webp']</value>
      <webElementGuid>15f36a69-3a56-4907-8934-4d691663d254</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
