<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_KANGGO - Aplikasi Tukang BangunanAplika_69ef48</name>
   <tag></tag>
   <elementGuidId>cd595795-e6d0-4994-9edc-b447c96d0d8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/article/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.vc_row.wpb_row.section.section-parallax.mt-0.mb-0.section-no-borders.porto-inner-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>71c58a65-a53f-4965-9b9d-1c1fd665f9e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vc_row wpb_row section section-parallax mt-0 mb-0 section-no-borders porto-inner-container</value>
      <webElementGuid>7e7b046c-cff6-4140-b0bb-de0026fbfbde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KANGGO - Aplikasi Tukang BangunanAplikasi tukang bangunan yang menghubungkan kebutuhan bangunan Anda dengan para tukang profesional dengan berbagai keahlian.Biarkan kami yang menangani kebutuhan perbaikan bangunan Anda, mulai dari perbaikan nat keramik yang bolong di kamar mandi, perbaikan talang air menjelang musim hujan, pengecatan kamar/ruangan, hingga renovasi dapur, dapat kami selesaikan dengan baik.Dengan dukungan mitra tukang yang profesional dan berkualitas, Kanggo berkomitmen untuk membantu segala kebutuhan perbaikan bangunan Anda, Download aplikasi kanggo, segala kebutuhan perbaikan bangunan Anda #TukangReadyToGo LEBIH LANJUT&lt;img width=&quot;360&quot; height=&quot;240&quot;   alt=&quot;tim-kanggo&quot; data-src=&quot;https://kanggo.id/wp-content/uploads/2022/01/360.webp&quot; class=&quot;vc_single_image-img attachment-full lazyload&quot; src=&quot;data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==&quot; />&lt;noscript>&lt;img width=&quot;360&quot; height=&quot;240&quot; src=&quot;https://kanggo.id/wp-content/uploads/2022/01/360.webp&quot; class=&quot;vc_single_image-img attachment-full&quot; alt=&quot;tim-kanggo&quot; /></value>
      <webElementGuid>37fe7cdd-d090-45f0-a959-fbb1601d11de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/article[@class=&quot;post-143 page type-page status-publish hentry&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;vc_row wpb_row section section-parallax mt-0 mb-0 section-no-borders porto-inner-container&quot;]</value>
      <webElementGuid>7caa52d6-866e-43dc-99b3-4cac8a89a6b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/article/div/div[2]</value>
      <webElementGuid>f2cae4a2-f252-42d6-b577-b14457439fb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gabung Mitra'])[3]/following::div[1]</value>
      <webElementGuid>b0e3d182-d07c-46ce-8191-5af7e420fefc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Klik di sini'])[1]/following::div[1]</value>
      <webElementGuid>1f99d8ce-519a-4fa3-bc84-29b5dececdc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/div/div[2]</value>
      <webElementGuid>8caaa8ce-fa36-438a-9eec-e7df32e2fee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'KANGGO - Aplikasi Tukang BangunanAplikasi tukang bangunan yang menghubungkan kebutuhan bangunan Anda dengan para tukang profesional dengan berbagai keahlian.Biarkan kami yang menangani kebutuhan perbaikan bangunan Anda, mulai dari perbaikan nat keramik yang bolong di kamar mandi, perbaikan talang air menjelang musim hujan, pengecatan kamar/ruangan, hingga renovasi dapur, dapat kami selesaikan dengan baik.Dengan dukungan mitra tukang yang profesional dan berkualitas, Kanggo berkomitmen untuk membantu segala kebutuhan perbaikan bangunan Anda, Download aplikasi kanggo, segala kebutuhan perbaikan bangunan Anda #TukangReadyToGo LEBIH LANJUT&lt;img width=&quot;360&quot; height=&quot;240&quot;   alt=&quot;tim-kanggo&quot; data-src=&quot;https://kanggo.id/wp-content/uploads/2022/01/360.webp&quot; class=&quot;vc_single_image-img attachment-full lazyload&quot; src=&quot;data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==&quot; />&lt;noscript>&lt;img width=&quot;360&quot; height=&quot;240&quot; src=&quot;https://kanggo.id/wp-content/uploads/2022/01/360.webp&quot; class=&quot;vc_single_image-img attachment-full&quot; alt=&quot;tim-kanggo&quot; />' or . = 'KANGGO - Aplikasi Tukang BangunanAplikasi tukang bangunan yang menghubungkan kebutuhan bangunan Anda dengan para tukang profesional dengan berbagai keahlian.Biarkan kami yang menangani kebutuhan perbaikan bangunan Anda, mulai dari perbaikan nat keramik yang bolong di kamar mandi, perbaikan talang air menjelang musim hujan, pengecatan kamar/ruangan, hingga renovasi dapur, dapat kami selesaikan dengan baik.Dengan dukungan mitra tukang yang profesional dan berkualitas, Kanggo berkomitmen untuk membantu segala kebutuhan perbaikan bangunan Anda, Download aplikasi kanggo, segala kebutuhan perbaikan bangunan Anda #TukangReadyToGo LEBIH LANJUT&lt;img width=&quot;360&quot; height=&quot;240&quot;   alt=&quot;tim-kanggo&quot; data-src=&quot;https://kanggo.id/wp-content/uploads/2022/01/360.webp&quot; class=&quot;vc_single_image-img attachment-full lazyload&quot; src=&quot;data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==&quot; />&lt;noscript>&lt;img width=&quot;360&quot; height=&quot;240&quot; src=&quot;https://kanggo.id/wp-content/uploads/2022/01/360.webp&quot; class=&quot;vc_single_image-img attachment-full&quot; alt=&quot;tim-kanggo&quot; />')]</value>
      <webElementGuid>7d3e0212-d593-47fb-9655-d9b8748e6125</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
