<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Inspirasi  Solusi</name>
   <tag></tag>
   <elementGuidId>96dab5a7-4e97-4bec-b03a-0c7c83e03e3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='nav-menu-item-3187']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-menu-item-3187 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>92d57bb9-8a5d-4ba2-a621-034e8b04dce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://kanggo.id/blog/</value>
      <webElementGuid>dd55d408-db5d-47ba-a4e5-7375e93b1711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Inspirasi &amp; Solusi</value>
      <webElementGuid>69326c75-e9ae-4d76-922a-043622dbc4b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-menu-item-3187&quot;)/a[1]</value>
      <webElementGuid>977b9d63-b95f-48d2-8cc5-f3eb25c0cafd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav-menu-item-3187']/a</value>
      <webElementGuid>062f5089-c9b1-4394-9513-05c2b7a511b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Inspirasi &amp; Solusi')]</value>
      <webElementGuid>abf4a368-d182-4046-ad01-914e2133af6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Harga'])[1]/following::a[1]</value>
      <webElementGuid>4c7c5e89-4ba5-449d-81da-db098e313bad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jasa Angkat Barang Berat'])[1]/following::a[2]</value>
      <webElementGuid>5669af04-5147-4397-9289-0a2c27c014c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pusat Bantuan'])[1]/preceding::a[1]</value>
      <webElementGuid>77e9ee33-aaa1-4b90-aaa3-f147edcefe8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gabung Mitra'])[1]/preceding::a[2]</value>
      <webElementGuid>08705ec7-6cf4-401d-bf7d-d7bda7ed9440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Inspirasi &amp; Solusi']/parent::*</value>
      <webElementGuid>97b2673a-0907-40ff-a956-499d9454eadb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://kanggo.id/blog/')]</value>
      <webElementGuid>06f10acd-f34d-4850-9ec6-b137f35fabe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>616c19c1-93dc-4d1f-ba6f-8ee065278fcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://kanggo.id/blog/' and (text() = 'Inspirasi &amp; Solusi' or . = 'Inspirasi &amp; Solusi')]</value>
      <webElementGuid>86d36415-6c13-474a-b8a2-6aa7b6a0bbca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
