<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Jasa Pasang Plafon Gypsum</name>
   <tag></tag>
   <elementGuidId>11658ec2-468e-41f2-825c-5d2d89f1b163</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='nav-menu-item-3179']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-menu-item-3179 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0323aa38-4351-4b38-ae49-e2977caadd5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://kanggo.id/layanan-kanggo/layanan-perbaikan-plafon/</value>
      <webElementGuid>416ac0dd-2fe8-4df2-b495-9b0d5d1513fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jasa Pasang Plafon Gypsum</value>
      <webElementGuid>ccb212b1-44fd-457f-b822-2912d1ec504a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-menu-item-3179&quot;)/a[1]</value>
      <webElementGuid>c21023f1-8b14-4d8e-aa52-b7587dc65b45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav-menu-item-3179']/a</value>
      <webElementGuid>3c9f00b4-a182-4f99-8ced-fece5aebd1ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Jasa Pasang Plafon Gypsum')]</value>
      <webElementGuid>ac8a3aea-5c16-48a5-b002-9631ff49dea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jasa Pipa Mampet &amp; Instalasi Pipa'])[1]/following::a[1]</value>
      <webElementGuid>ab42f517-0722-4a74-95fa-b6d4cc9c97fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Layanan'])[1]/following::a[2]</value>
      <webElementGuid>012ca117-90fc-49e5-9532-49fc97d8cb3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jasa Pasang Pintu &amp; Perbaikan'])[1]/preceding::a[1]</value>
      <webElementGuid>e9c1f61d-553c-48bb-a98b-6fd9af7fc47b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jasa Pasang Keramik'])[1]/preceding::a[2]</value>
      <webElementGuid>c9aac018-cb0f-4140-a49a-08563d0b7adb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jasa Pasang Plafon Gypsum']/parent::*</value>
      <webElementGuid>74681dfa-75a6-4b94-b8ef-d2e19ecd0dbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://kanggo.id/layanan-kanggo/layanan-perbaikan-plafon/')]</value>
      <webElementGuid>8417ae6d-964e-4b0d-a8a5-f2794aeacf5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/ul/li[2]/a</value>
      <webElementGuid>c5ce397f-c809-4ba0-b5e6-af63ee267d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://kanggo.id/layanan-kanggo/layanan-perbaikan-plafon/' and (text() = 'Jasa Pasang Plafon Gypsum' or . = 'Jasa Pasang Plafon Gypsum')]</value>
      <webElementGuid>d631548a-a9cf-4098-be33-e23d52104353</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
