<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Layanan</name>
   <tag></tag>
   <elementGuidId>9c9e56d3-2da6-48cc-a404-af69c840486c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='nav-menu-item-3176']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-menu-item-3176 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4f10728b-dc31-47cd-901c-d4a9c06696a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://kanggo.id/layanan-kanggo/</value>
      <webElementGuid>a96c073a-8932-4386-847c-2d2c3072c5ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Layanan</value>
      <webElementGuid>a30d9d3a-f89e-48f2-9a37-e909ca2f5cfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-menu-item-3176&quot;)/a[1]</value>
      <webElementGuid>ed537fda-3860-484c-bdda-77004733561a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav-menu-item-3176']/a</value>
      <webElementGuid>ff0b8fca-9e93-4311-a8a0-76993d5b1fed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Layanan')]</value>
      <webElementGuid>86bb69aa-6fbd-4e32-8310-eef858e6bce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tentang Kami'])[1]/following::a[1]</value>
      <webElementGuid>2c19043f-2cf5-4a1f-bce9-36169cc4fe8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jasa Pipa Mampet &amp; Instalasi Pipa'])[1]/preceding::a[1]</value>
      <webElementGuid>5e97be58-b485-43a9-b634-e253ca0b99d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jasa Pasang Plafon Gypsum'])[1]/preceding::a[2]</value>
      <webElementGuid>1580b9af-b565-419f-9a58-146f6b043125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Layanan']/parent::*</value>
      <webElementGuid>1b83d140-4a25-4cac-80f4-f45924afcc68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://kanggo.id/layanan-kanggo/')]</value>
      <webElementGuid>bf22c258-f287-434e-a9d2-6ff636e0ce85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>319737ed-f72f-46b0-b4be-7aeb267bde5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://kanggo.id/layanan-kanggo/' and (text() = 'Layanan' or . = 'Layanan')]</value>
      <webElementGuid>c688cc2d-ae7d-4c24-8396-5c312cd81aef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
