<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Tentang Kami_img-responsive standard-lo_27995f</name>
   <tag></tag>
   <elementGuidId>8b4851c5-73fc-48a7-a262-785bfa25bee9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/div/div/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.img-responsive.standard-logo.retina-logo.lazy-loaded.lazyloaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>94a1a8b0-b04a-44c5-a7e0-4f6a5ef7437c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Kanggo – Perbaiki Rumah, Berikan Pekerjaan</value>
      <webElementGuid>88a1f648-42d8-4819-87a2-253f7477ef9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>//kanggo.id/wp-content/uploads/2022/02/logo-kanggo-287-x-81.webp</value>
      <webElementGuid>d8200c4b-0594-4022-8c1c-25152ad16def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-responsive standard-logo retina-logo lazy-loaded lazyloaded</value>
      <webElementGuid>e143bb93-4c7a-4cc8-a439-e42ab30ab1fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//kanggo.id/wp-content/uploads/2022/02/logo-kanggo-287-x-81.webp</value>
      <webElementGuid>9289ab77-43ad-4916-953b-03e8a803edb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;header-main&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;header-left&quot;]/div[@class=&quot;logo logo-transition&quot;]/a[1]/img[@class=&quot;img-responsive standard-logo retina-logo lazy-loaded lazyloaded&quot;]</value>
      <webElementGuid>6b320c1b-e40f-4f25-a8ba-47bac6400a55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div/div/div/div/a/img</value>
      <webElementGuid>5331960e-0628-44d7-b41c-7738c027cfff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Kanggo – Perbaiki Rumah, Berikan Pekerjaan']</value>
      <webElementGuid>d8a36b48-c1eb-4316-824d-80c7ebf32962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>880076d6-3f38-47bb-9db1-17b7dfc1948c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Kanggo – Perbaiki Rumah, Berikan Pekerjaan' and @src = '//kanggo.id/wp-content/uploads/2022/02/logo-kanggo-287-x-81.webp']</value>
      <webElementGuid>0f764982-3b09-48b0-9ae1-559ab2096dbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
