<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_home improvement_vc_single_image-img at_a7b092_1_2_3_4_5_6_7</name>
   <tag></tag>
   <elementGuidId>4e9b32f3-601f-4193-8c13-a32a9f0715d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/article/div/div/div/div/div[4]/div/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>720277e7-b69b-488c-b09e-1c61bae2b8f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>331</value>
      <webElementGuid>d8a5f335-b667-44b4-b394-a04efa03698b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>358</value>
      <webElementGuid>ed0b1880-2619-42e3-bd4f-aa3012364620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://kanggo.id/wp-content/uploads/2022/01/tk-listrik.webp</value>
      <webElementGuid>afab28aa-4902-4b82-8b37-ed5fa3db289e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>3233fcb2-bd25-4db7-86a3-e20fc95a7469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://kanggo.id/wp-content/uploads/2022/01/tk-listrik.webp</value>
      <webElementGuid>82755e27-6831-47a2-a286-16112a15efbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vc_single_image-img attachment-full lazy-loaded</value>
      <webElementGuid>0d043c2d-dd4c-4233-8a4c-c97ef52b6432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/article[@class=&quot;post-2071 page type-page status-publish hentry&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;vc_row wpb_row row&quot;]/div[@class=&quot;vc_column_container col-md-12&quot;]/div[@class=&quot;wpb_wrapper vc_column-inner&quot;]/div[@class=&quot;vc_row wpb_row vc_inner row&quot;]/div[@class=&quot;vc_column_container col-md-3&quot;]/div[@class=&quot;wpb_wrapper vc_column-inner&quot;]/div[@class=&quot;wpb_single_image wpb_content_element vc_align_left&quot;]/div[@class=&quot;wpb_wrapper&quot;]/div[@class=&quot;vc_single_image-wrapper   vc_box_border_grey&quot;]/img[@class=&quot;vc_single_image-img attachment-full lazy-loaded&quot;]</value>
      <webElementGuid>aa65a2a8-7339-434a-ba7b-433621c3a788</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/article/div/div/div/div/div[4]/div/div/div/div/div/img</value>
      <webElementGuid>4d4286d2-a398-47a0-853c-cda95e0b9673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://kanggo.id/wp-content/uploads/2022/01/tk-listrik.webp')]</value>
      <webElementGuid>e1e70c9d-f34d-451f-bb25-c1ecf64fa977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/img</value>
      <webElementGuid>5486eeac-9d02-43b0-ab1b-0a249b3a03da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://kanggo.id/wp-content/uploads/2022/01/tk-listrik.webp']</value>
      <webElementGuid>a6866fbd-b13f-497d-bbf2-30f5f8deebc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
