<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_home improvement_vc_single_image-img at_a7b092_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>009898a2-4a82-451e-bf44-b94b4a4d7e10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/article/div/div/div/div/div[3]/div/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>dbd7bda2-11d3-460e-b906-11ddbd822080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>331</value>
      <webElementGuid>10021aba-c14b-4c71-ada3-a50c89aab04c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>358</value>
      <webElementGuid>6279e774-7f4d-4c44-87e5-3323585212a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://kanggo.id/wp-content/uploads/2022/01/tk-cat.webp</value>
      <webElementGuid>535571da-eeb6-4b2f-a981-15d1ce907c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>464cc727-7139-4755-9178-33a956189b0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://kanggo.id/wp-content/uploads/2022/01/tk-cat.webp</value>
      <webElementGuid>a03f4681-ba48-46a6-a999-90bdaab55cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vc_single_image-img attachment-full lazy-loaded</value>
      <webElementGuid>83f9c4ef-17d9-4578-8846-86de38cce395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/article[@class=&quot;post-2071 page type-page status-publish hentry&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;vc_row wpb_row row&quot;]/div[@class=&quot;vc_column_container col-md-12&quot;]/div[@class=&quot;wpb_wrapper vc_column-inner&quot;]/div[@class=&quot;vc_row wpb_row vc_inner row&quot;]/div[@class=&quot;vc_column_container col-md-3&quot;]/div[@class=&quot;wpb_wrapper vc_column-inner&quot;]/div[@class=&quot;wpb_single_image wpb_content_element vc_align_left&quot;]/div[@class=&quot;wpb_wrapper&quot;]/div[@class=&quot;vc_single_image-wrapper   vc_box_border_grey&quot;]/img[@class=&quot;vc_single_image-img attachment-full lazy-loaded&quot;]</value>
      <webElementGuid>7ad3392d-05a9-4543-a363-8fb565fc741d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/article/div/div/div/div/div[3]/div/div/div/div/div/img</value>
      <webElementGuid>c6cfcdb8-6a13-4abd-9fef-40768d40ecb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://kanggo.id/wp-content/uploads/2022/01/tk-cat.webp')]</value>
      <webElementGuid>a9a0fef2-24e7-4958-a323-f7ad0c5f2498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/img</value>
      <webElementGuid>974d502c-9e6d-4c13-a47e-decfab072558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://kanggo.id/wp-content/uploads/2022/01/tk-cat.webp']</value>
      <webElementGuid>2a7cb6a2-186f-4cc7-b661-eb46f38f3105</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
