<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_home improvement_vc_single_image-img at_66105c</name>
   <tag></tag>
   <elementGuidId>744ef41e-8d30-497e-8c96-770ff2eb6b2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/article/div/div/div/div/div[3]/div[4]/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.vc_single_image-img.attachment-large.lazy-loaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e6933ec6-1231-443b-9660-f98cd311938e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>331</value>
      <webElementGuid>a1d2add5-374e-4c77-a761-c019131ce125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>358</value>
      <webElementGuid>b75018f4-4ffb-4300-91ff-1af91a3a630d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://kanggo.id/wp-content/uploads/2022/01/tk-keramik-2.webp</value>
      <webElementGuid>00a054eb-e8fe-4d99-be57-54ea89620b4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>010fbb07-6d2f-4891-9092-d3b773d92f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://kanggo.id/wp-content/uploads/2022/01/tk-keramik-2.webp</value>
      <webElementGuid>adcc988f-fd6b-44dc-aeb8-cc993ed563fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vc_single_image-img attachment-large lazy-loaded</value>
      <webElementGuid>b7305a1a-338a-4389-b433-eadb62bc4a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/article[@class=&quot;post-2071 page type-page status-publish hentry&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;vc_row wpb_row row&quot;]/div[@class=&quot;vc_column_container col-md-12&quot;]/div[@class=&quot;wpb_wrapper vc_column-inner&quot;]/div[@class=&quot;vc_row wpb_row vc_inner row&quot;]/div[@class=&quot;vc_column_container col-md-3&quot;]/div[@class=&quot;wpb_wrapper vc_column-inner&quot;]/div[@class=&quot;wpb_single_image wpb_content_element vc_align_left&quot;]/div[@class=&quot;wpb_wrapper&quot;]/div[@class=&quot;vc_single_image-wrapper   vc_box_border_grey&quot;]/img[@class=&quot;vc_single_image-img attachment-large lazy-loaded&quot;]</value>
      <webElementGuid>66566cbe-2853-4bb9-bab7-cc6db4fa47f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/article/div/div/div/div/div[3]/div[4]/div/div/div/div/img</value>
      <webElementGuid>c0592e3a-4eb7-4f1c-9a76-b0c33689aa70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://kanggo.id/wp-content/uploads/2022/01/tk-keramik-2.webp')]</value>
      <webElementGuid>39d88219-e502-4b5b-b996-44e07c13cfb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[4]/div/div/div/div/img</value>
      <webElementGuid>7cbdbe9c-2291-4eee-b9c2-f8da4e9caa5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://kanggo.id/wp-content/uploads/2022/01/tk-keramik-2.webp']</value>
      <webElementGuid>37c85d32-06c2-4aad-8071-455d743340b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
