<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_home improvement_vc_single_image-img at_a7b092_1_2_3_4_5_6_7_8</name>
   <tag></tag>
   <elementGuidId>2bfc0a21-2b43-481c-8888-5ea34ae9b514</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/article/div/div/div/div/div[4]/div[2]/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>031b31ab-c78b-4529-984a-b72afbf4c737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>331</value>
      <webElementGuid>723b4edb-841f-486f-bf68-c924c7a88a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>358</value>
      <webElementGuid>45229947-3a0e-46e3-bf08-40629f956de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://kanggo.id/wp-content/uploads/2022/01/tk-pipa.webp</value>
      <webElementGuid>b8652b75-16c2-4791-9c0e-ce3f681b3452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>144c51bf-ac2a-4c89-b520-47796819197d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://kanggo.id/wp-content/uploads/2022/01/tk-pipa.webp</value>
      <webElementGuid>cc6fcfa8-3a5e-4ff7-a6af-e3b31970854e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vc_single_image-img attachment-full lazy-loaded</value>
      <webElementGuid>1f309576-757d-4d7c-9d88-53bcd2666431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/article[@class=&quot;post-2071 page type-page status-publish hentry&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;vc_row wpb_row row&quot;]/div[@class=&quot;vc_column_container col-md-12&quot;]/div[@class=&quot;wpb_wrapper vc_column-inner&quot;]/div[@class=&quot;vc_row wpb_row vc_inner row&quot;]/div[@class=&quot;vc_column_container col-md-3&quot;]/div[@class=&quot;wpb_wrapper vc_column-inner&quot;]/div[@class=&quot;wpb_single_image wpb_content_element vc_align_left&quot;]/div[@class=&quot;wpb_wrapper&quot;]/div[@class=&quot;vc_single_image-wrapper   vc_box_border_grey&quot;]/img[@class=&quot;vc_single_image-img attachment-full lazy-loaded&quot;]</value>
      <webElementGuid>50dab9bf-c182-41b9-bf99-93c88b9b39b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/article/div/div/div/div/div[4]/div[2]/div/div/div/div/img</value>
      <webElementGuid>f67fb622-13d7-403b-9fa8-6548011ea3e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://kanggo.id/wp-content/uploads/2022/01/tk-pipa.webp')]</value>
      <webElementGuid>fde3d4bd-84ae-4cfc-9479-a6f3d5c11763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/div/div/img</value>
      <webElementGuid>1613a39b-ed18-4755-900c-62538504f3cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://kanggo.id/wp-content/uploads/2022/01/tk-pipa.webp']</value>
      <webElementGuid>a3c22359-dcb1-47f5-b712-471d060deff5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
