<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_home improvement_vc_single_image-img at_a7b092_1</name>
   <tag></tag>
   <elementGuidId>2057ddc0-71e9-4058-8ce9-af241082d4ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/article/div/div/div/div/div[2]/div[2]/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.vc_column_container.col-md-3.vc_custom_1616753512592 > div.wpb_wrapper.vc_column-inner > div.wpb_single_image.wpb_content_element.vc_align_left > div.wpb_wrapper > div.vc_single_image-wrapper.vc_box_border_grey > img.vc_single_image-img.attachment-full.lazy-loaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>af89fe53-e525-4a95-b811-44f1643f5541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>332</value>
      <webElementGuid>73edba02-dd9f-4876-9ddf-ae1cabb39760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>358</value>
      <webElementGuid>67e76fb5-6292-4d87-aefd-48958ae11fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://kanggo.id/wp-content/uploads/2022/01/tk-aluminium.webp</value>
      <webElementGuid>2af295ae-0633-4ade-9cdc-67d2626a7c36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>26e744cd-888e-47e5-b3a9-0619ffbb9592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://kanggo.id/wp-content/uploads/2022/01/tk-aluminium.webp</value>
      <webElementGuid>1fa9d551-28f7-41d1-9543-ff03488f2729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vc_single_image-img attachment-full lazy-loaded</value>
      <webElementGuid>e50c1fff-60a9-4e11-912f-0cdaae5a492c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/article[@class=&quot;post-2071 page type-page status-publish hentry&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;vc_row wpb_row row&quot;]/div[@class=&quot;vc_column_container col-md-12&quot;]/div[@class=&quot;wpb_wrapper vc_column-inner&quot;]/div[@class=&quot;vc_row wpb_row vc_inner row&quot;]/div[@class=&quot;vc_column_container col-md-3 vc_custom_1616753512592&quot;]/div[@class=&quot;wpb_wrapper vc_column-inner&quot;]/div[@class=&quot;wpb_single_image wpb_content_element vc_align_left&quot;]/div[@class=&quot;wpb_wrapper&quot;]/div[@class=&quot;vc_single_image-wrapper   vc_box_border_grey&quot;]/img[@class=&quot;vc_single_image-img attachment-full lazy-loaded&quot;]</value>
      <webElementGuid>e6f9f001-0860-4f88-8e83-899097081e81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/article/div/div/div/div/div[2]/div[2]/div/div/div/div/img</value>
      <webElementGuid>395e335d-d5c5-4488-95a7-74f755fe2e2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://kanggo.id/wp-content/uploads/2022/01/tk-aluminium.webp')]</value>
      <webElementGuid>7291f871-3808-4d26-87c7-e18df818ac8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/img</value>
      <webElementGuid>ca814321-d348-4565-8389-46afb088d665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://kanggo.id/wp-content/uploads/2022/01/tk-aluminium.webp']</value>
      <webElementGuid>8179b577-48b4-4f0b-a4d7-06daaac3a398</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
